name: faker_app_flutter_firebase
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5
  flutter_riverpod: 2.3.10
  go_router: 10.1.1
  equatable: 2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2

flutter:
  uses-material-design: true
